// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validar se as variáveis de ambiente estão configuradas e são strings válidas
const isSupabaseConfigured = 
  SUPABASE_URL && 
  SUPABASE_PUBLISHABLE_KEY && 
  typeof SUPABASE_URL === 'string' && 
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' &&
  SUPABASE_URL.length > 0 &&
  SUPABASE_PUBLISHABLE_KEY.length > 0;

// Criar cliente apenas se as variáveis estiverem configuradas
// Caso contrário, retornar null para evitar erros
let supabaseInstance: SupabaseClient<Database> | null = null;

if (isSupabaseConfigured) {
  try {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (error) {
    console.error('Erro ao criar cliente Supabase:', error);
    supabaseInstance = null;
  }
} else if (import.meta.env.DEV) {
  // Log de aviso apenas em desenvolvimento
  console.warn(
    '⚠️ Supabase não está configurado. ' +
    'Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no arquivo .env\n' +
    'O aplicativo funcionará normalmente com autenticação local (localStorage).'
  );
}

export const supabase = supabaseInstance;

// Função helper para verificar se Supabase está configurado e pronto
export const isSupabaseReady = () => supabaseInstance !== null;